/* 
 * Swagger Demo
 *
 * Swagger的简单示例, 包括swagger-codegen, swagger2markup 和 asciidoctor.
 *
 * OpenAPI spec version: v1
 * Contact: damon.q@iv66.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Book struct {

	// 作者
	Author string `json:"author,omitempty"`

	CategoryId int32 `json:"categoryId,omitempty"`

	Id int32 `json:"id,omitempty"`

	// 书名
	Name string `json:"name,omitempty"`
}
