/*
 * Swagger Demo
 * Swagger的简单示例, 包括swagger-codegen, swagger2markup 和 asciidoctor.
 *
 * OpenAPI spec version: v1
 * Contact: damon.q@iv66.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Book;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BookApiApi
 */
@Ignore
public class BookApiApiTest {

    private final BookApiApi api = new BookApiApi();

    
    /**
     * 根据ID获取书籍
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBookByIdUsingGETTest() throws ApiException {
        Integer id = null;
        Book response = api.getBookByIdUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * 根据分类获取书籍
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBooksByCategoryUsingGETTest() throws ApiException {
        Integer id = null;
        List<Book> response = api.getBooksByCategoryUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * 更新书籍
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateUsingPOSTTest() throws ApiException {
        Integer id = null;
        Boolean response = api.updateUsingPOST(id);

        // TODO: test validations
    }
    
}
