/*
 * Swagger Demo
 * Swagger的简单示例, 包括swagger-codegen, swagger2markup 和 asciidoctor.
 *
 * OpenAPI spec version: v1
 * Contact: damon.q@iv66.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Category;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CategoryApiApi
 */
@Ignore
public class CategoryApiApiTest {

    private final CategoryApiApi api = new CategoryApiApi();

    
    /**
     * 获取全部分类
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUsingGETTest() throws ApiException {
        List<Category> response = api.getAllUsingGET();

        // TODO: test validations
    }
    
    /**
     * 根据ID获取分类
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUsingGETTest() throws ApiException {
        Integer id = null;
        Category response = api.getUsingGET(id);

        // TODO: test validations
    }
    
}
